# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1a0d468f0859e5038c5205e6f1dd4aa0732c816a10a4bee9d369ea7ddcda7f30aa89e94e4f4a8d53959149b1cba4b47caafdda375699206fd5565adf07f20892
  vkontakte_app_id: 6426717
  vkontakte_app_secret: O73VzjLULmiLbm4pouvz
  twitter_app_id: UnBiwa4LvERnPKDWk0Jt6Rzgu
  twitter_app_secret: SUXeML2RKlwCexXR4dJib2BPcrld67MlA0imRKWtECTgquDkQr

test:
  secret_key_base: c4061df3a5df0f14e2c0f15601150d4e01f5238cf4de7ceb53a8b8793be280faabcde529c854594f7c27fc51736ed68eb6929b49f95dfa398d933afbe76bcae8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 1a0d468f0859e5038c5205e6f1dd4aa0732c816a10a4bee9d369ea7ddcda7f30aa89e94e4f4a8d53959149b1cba4b47caafdda375699206fd5565adf07f20892
  vkontakte_app_id: 6426717
  vkontakte_app_secret: O73VzjLULmiLbm4pouvz
  twitter_app_id: UnBiwa4LvERnPKDWk0Jt6Rzgu
  twitter_app_secret: SUXeML2RKlwCexXR4dJib2BPcrld67MlA0imRKWtECTgquDkQr
